"use client";

const province = [
  { label: "--Please choose an option--", value: "" },
  { label: "Banteay Meanchey", value: "Banteay_Meanchey" },
  { label: "Battambang", value: "Battambang" },
  { label: "Kampong Cham", value: "Kampong_Cham" },
  { label: "Kampong Chhnang", value: "Kampong_Chhnang" },
  { label: "Kampong Speu", value: "Kampong_Speu" },
  { label: "Kampong Thom", value: "Kampong_Thom" },
  { label: "Kampot", value: "Kampot" },
  { label: "Kandal", value: "Kandal" },
  { label: "Kep", value: "Kep" },
  { label: "Koh Kong", value: "Koh_Kong" },
  { label: "Kracheh", value: "Kracheh" },
  { label: "Mondulkiri", value: "Mondulkiri" },
  { label: "Oddar Meanchey", value: "Oddar_Meanchey" },
  { label: "Pailin", value: "Pailin" },
  { label: "Phnom Penh", value: "Phnom_Penh" },
  { label: "Preah Vihear", value: "Preah_Vihear" },
  { label: "Pursat", value: "Pursat" },
  { label: "Prey Veng", value: "Prey_Veng" },
  { label: "Ratanakiri", value: "Ratanakiri" },
  { label: "Siem Reap", value: "Siem_Reap" },
  { label: "Preah Sihanouk", value: "Preah_Sihanouk" },
  { label: "Stung Treng", value: "Stung_Treng" },
  { label: "Svay Rieng", value: "Svay_Rieng" },
  { label: "Takéo", value: "Takéo" },
  { label: "Tboung Khmum", value: "Tboung_Khmum" },
] as const;

type DistrictsByProvince = {
  [key: string]: string[];
};
const district: DistrictsByProvince = {
  Banteay_Meanchey: [
    "Mongkol Borei",
    "Phnum Srok",
    "Preah Netr Preah",
    "Ou Chrov",
    "Serei Saophoan",
    "Thma Puok",
    "Svay Chek",
    "Malai",
    "Paoy Paet",
  ],
  Battambang: [
    "Banan",
    "Thma Koul",
    "Bavel",
    "Aek Phnum",
    "Moung Ruessei",
    "Rotonak Mondol",
    "Sangkae",
    "Samlout",
    "Sampov Lun",
    "Phnum Proek",
    "Kamrieng",
    "Koas Krala",
    "Rukh Kiri",
  ],
  Kampong_Cham: [
    "Batheay",
    "Chamkar Leu",
    "Cheung Prey",
    "Kampong Cham",
    "Kampong Siem",
    "Kang Meas",
    "Kaoh Soutin",
    "Prey Chhor",
    "Srei Santhor",
    "Stueng Trang",
  ],
  Kampong_Chhnang: [
    "Baribour",
    "Chol Kiri",
    "Kampong Chhnang",
    "Kampong Leaeng",
    "Kampong Tralach",
    "Rolea B'ier",
    "Sameakki Mean Chey",
    "Tuek Phos",
  ],
  Kampong_Speu: [
    "Basedth",
    "Chbar Mon",
    "Kong Pisei",
    "Aoral",
    "Phnum Sruoch",
    "Samraong Tong",
    "Thpong",
    "Odongk Maechay",
    "Samkkei Munichay",
  ],
  Kampong_Thom: [
    "Baray",
    "Kampong Svay",
    "Stueng Saen",
    "Prasat Ballangk",
    "Prasat Sambour",
    "Sandan",
    "Santuk",
    "Stoung",
    "Taing Kouk",
  ],
  Kampot: [
    "Angkor Chey",
    "Banteay Meas",
    "Chhuk",
    "Chum Kiri",
    "Dang Tong",
    "Kampong Trach",
    "Tuek Chhou",
    "Kampot",
    "Bokor",
  ],
  Kandal: [
    "Kandal Stueng",
    "Kien Svay",
    "Khsach Kandal",
    "Chum Kiri",
    "Leuk Daek",
    "Lvea Aem",
    "Mukh Kampul",
    "Angk Snuol",
    "Ponhea Lueu",
    "S'ang",
    "Ta Khmau",
    "Sampeou Poun",
    "Akreiy Ksatr",
  ],
  Kep: ["Damnak Chang'aeur", "Kaeb"],
  Kracheh: [
    "Chhloung",
    "Kracheh",
    "Prek Prasab",
    "Sambour",
    "Snuol",
    "Chetr Borei",
    "Ou Krieng Saenchey",
  ],
  Mondulkiri: [
    "Kaev Seima",
    "Kaoh Nheaek",
    "Ou Reang",
    "Pech Chreada",
    "Saen Monourom",
    "Chetr Borei",
    "Ou Krieng Saenchey",
  ],
  Oddar_Meanchey: [
    "Anlong Veaeng",
    "Banteay Ampil",
    "Chong Kal",
    "Samraong",
    "Trapeang Prasat",
  ],
  Preah_Vihear: [
    "Chey Saen",
    "Chhaeb",
    "Choam Khsant",
    "Kuleaen",
    "Rovieng",
    "Sangkom Thmei",
    "Tbaeng Meanchey",
    "Preah Vihear Municipality",
  ],
  Pailin: ["Pailin", "Sala Krau"],
  Phnom_Penh: [
    "Chamkar Mon",
    "Doun Penh",
    "Prampir Meakkakra",
    "Tuol Kouk",
    "Dangkao",
    "Mean Chey",
    "Russey Keo",
    "Saensokh",
    "Pur SenChey",
    "Chraoy Chongvar",
    "Praek Pnov",
    "Chbar Ampov",
    "Boeng Keng Kang",
    "Kamboul",
  ],
  Pursat: [
    "Bakan",
    "Kandieng",
    "Krakor",
    "Phnum Kravanh",
    "Pursat",
    "Veal Veaeng",
    "Ta Lou Senchey",
  ],
  Prey_Veng: [
    "Ba Phnum",
    "Kamchay Mear",
    "Kampong Trabaek",
    "Kanhchriech",
    "Me Sang",
    "Peam Chor",
    "Peam Ro",
    "Pea Reang",
    "Preah Sdach",
    "Prey Veng",
    "Pur Rieng",
    "Sithor Kandal",
    "Svay Antor",
  ],
  Ratanakiri: [
    "Andoung Meas",
    "Ban Lung",
    "Bar Kaev",
    "Koun Mom",
    "Lumphat",
    "Ou Chum",
    "Ou Ya Dav",
    "Ta Veaeng",
    "Veun Sai",
  ],
  Siem_Reap: [
    "Angkor Chum",
    "Angkor Thum",
    "Banteay Srei",
    "Chi Kraeng",
    "Kralanh",
    "Puok",
    "Prasat Bakong",
    "Siem Reap",
    "Soutr Nikom",
    "Srei Snam",
    "Svay Leu",
    "Varin",
  ],
  Preah_Sihanouk: [
    "Preah Sihanouk",
    "Prey Nob",
    "Stueng Hav",
    "Kampong Seila",
    "Kaoh Rung",
  ],
  Stung_Treng: [
    "Sesan",
    "Siem Bouk",
    "Siem Pang",
    "Stueng Traeng",
    "Thala Barivat",
    "Borei Ou Svay Senchey",
  ],
  Svay_Rieng: [
    "Chantrea",
    "Kampong Rou",
    "Rumduol",
    "Romeas Haek",
    "Svay Chrum",
    "Svay Rieng",
    "Svay Teab",
    "Bavet",
  ],
  Takéo: [
    "Angkor Borei",
    "Bati",
    "Borei Cholsar",
    "Kiri Vong",
    "Kaoh Andaet",
    "Prey Kabbas",
    "Samraong",
    "Doun Kaev",
    "Tram Kak",
    "Treang",
  ],
  Tboung_Khmum: [
    "Dambae",
    "Krouch Chhmar",
    "Memot",
    "Ou Reang Ov",
    "Ponhea Kraek",
    "Suong",
    "Tboung Khmum",
  ],
};

export { district, province };
